export const MTRXCTL_STORE_VALUE = "MTRXCTL_STORE_VALUE";
export const MTRXCTL_SUBMIT_REQUEST = "MTRXCTL_SUBMIT_REQUEST";
export const MTRXCTL_SUBMIT_SUCCESS = "MTRXCTL_SUBMIT_SUCCESS";
export const MTRXCTL_SUBMIT_ERROR = "MTRXCTL_SUBMIT_ERROR";
export const MTRXCTL_CLEAR = "MTRXCTL_CLEAR";
export const MTRXCTL_STORE_MATRIX_DATA = "MTRXCTL_STORE_MATRIX_DATA";
export const MTRXCTL_ROOM_LIST_INITIALIZE = "MTRXCTL_ROOM_LIST_INITIALIZE";
export const MTRXCTL_ROOM_LIST_PUT = "MTRXCTL_ROOM_LIST_PUT";
export const MTRXCTL_ROOM_LIST_DELETE = "MTRXCTL_ROOM_LIST_DELETE";
export const MTRXCTL_ROOM_META_STORE = "MTRXCTL_ROOM_META_STORE";
export const MTRXCTL_SET_SELECTED_ROOM = "MTRXCTL_SET_SELECTED_ROOM";
export const MTRXCTL_DEVICE_VERIFICATION_STORE = "MTRXCTL_DEVICE_VERIFICATION_STORE";

export const AUTHCTL_SUBMIT_REQUEST = "AUTHCTL_SUBMIT_REQUEST";
export const AUTHCTL_SUBMIT_SUCCESS = "AUTHCTL_SUBMIT_SUCCESS";
export const AUTHCTL_SUBMIT_ERROR = "AUTHCTL_SUBMIT_ERROR";
export const AUTHCTL_CLEAR = "AUTHCTL_CLEAR";
export const AUTHCTL_STORE_VALUE = "AUTHCTL_STORE_VALUE";
// OIDC (OAuth 2.0) через authentik — вход, общий для приложения: AUTHCTL_ получает
// loginToken, сессию Matrix по нему поднимает MTRXCTL_ (мост — в AuthContainer).
// READY — токен получен и ждёт запуска, SUCCESS — сессия по нему поднята (токен израсходован)
export const AUTHCTL_OIDC_REQUEST = "AUTHCTL_OIDC_REQUEST";
export const AUTHCTL_OIDC_READY = "AUTHCTL_OIDC_READY";
export const AUTHCTL_OIDC_SUCCESS = "AUTHCTL_OIDC_SUCCESS";
export const AUTHCTL_OIDC_ERROR = "AUTHCTL_OIDC_ERROR";
export const AUTHCTL_OIDC_CLEAR = "AUTHCTL_OIDC_CLEAR";
// Явный выбор источника матричных учётных данных (REST-пара или loginToken authentik)
export const AUTHCTL_SELECT_AUTH_SOURCE = "AUTHCTL_SELECT_AUTH_SOURCE";
