export const MTRXCTL_STORE_VALUE        = 'MTRXCTL_STORE_VALUE'
export const MTRXCTL_ERROR_ALERT        = 'MTRXCTL_ERROR_ALERT'

export const AUTHCTL_SUBMIT_REQUEST     = 'AUTHCTL_SUBMIT_REQUEST'
export const AUTHCTL_SUBMIT_SUCCESS     = 'AUTHCTL_SUBMIT_SUCCESS'
export const AUTHCTL_SUBMIT_ERROR       = 'AUTHCTL_SUBMIT_ERROR'
export const AUTHCTL_CLEAR              = 'AUTHCTL_CLEAR'
export const AUTHCTL_STORE_VALUE        = 'AUTHCTL_STORE_VALUE'
